# Generated by Django 6.1 on 2026-08-30 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('origin_city', models.CharField(default='Lagos', max_length=100)),
                ('destination_city', models.CharField(default='Abuja', max_length=100)),
                ('service_type', models.CharField(choices=[('INTERSTATE', 'Interstate Heavy Haulage'), ('EXPRESS', 'Last-Mile Express Delivery'), ('COLD_CHAIN', 'Cold Storage & Temperature Controlled'), ('MARITIME', 'Apapa & Port Freight Clearance')], default='INTERSTATE', max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('status', models.CharField(choices=[('BOOKED', 'Order Received'), ('DISPATCHED', 'Dispatched from Hub'), ('IN_TRANSIT', 'In Transit'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], default='IN_TRANSIT', max_length=30)),
                ('current_lat', models.FloatField(default=7.3775)),
                ('current_lng', models.FloatField(default=3.947)),
                ('current_location_name', models.CharField(default='Lagos-Ibadan Expressway, Km 45', max_length=200)),
                ('speed_kmh', models.IntegerField(default=78)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, default=4.5, max_digits=4, null=True)),
                ('driver_name', models.CharField(default='Captain Emeka Okafor', max_length=100)),
                ('driver_phone', models.CharField(default='+234 803 456 7890', max_length=20)),
                ('truck_number', models.CharField(default='BHL-TRK-902-NG', max_length=30)),
                ('estimated_delivery', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('passed', models.BooleanField(default=False)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='tracking.shipment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
