# Generated by Django 6.1 on 2026-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cargo_value_naira', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('includes_insurance', models.BooleanField(default=False)),
                ('calculated_amount_naira', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_days', models.IntegerField(default=2)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
